### ISSUE TITLE
需求意见

### ISSUE THREAD

**Issue by qqbaiduer** [xfstart07/gocrontab#1]
能否增加添加任务时支持带参数的功能？

例如：https://github.com/jasonlvhit/gocron/blob/master/gocron.go

func taskWithParams(a int, b string) {
	fmt.Println(a, b)
}

func main() {
	gocron.Every(1).Second().Do(taskWithParams, 1, "hello")
}

**Comment by xfstart07** [comment]
@qqbaiduer 谢谢你的意见，我已经在新的版本里面添加了这个功能
